<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    static array $data = [
        // Mantener Ecuador con IdPais=52 por dependencias en otros seeders.
        ['Ecuador', 1, 52],

        // America
        ['Antigua y Barbuda', 1],
        ['Argentina', 1],
        ['Bahamas', 1],
        ['Barbados', 1],
        ['Belice', 1],
        ['Bolivia', 1],
        ['Brasil', 1],
        ['Canadá', 1],
        ['Chile', 1],
        ['Colombia', 1],
        ['Costa Rica', 1],
        ['Cuba', 1],
        ['Dominica', 1],
        ['El Salvador', 1],
        ['Estados Unidos', 1],
        ['Granada', 1],
        ['Guatemala', 1],
        ['Guyana', 1],
        ['Haití', 1],
        ['Honduras', 1],
        ['Jamaica', 1],
        ['México', 1],
        ['Nicaragua', 1],
        ['Panamá', 1],
        ['Paraguay', 1],
        ['Perú', 1],
        ['República Dominicana', 1],
        ['San Cristóbal y Nieves', 1],
        ['San Vicente y las Granadinas', 1],
        ['Santa Lucía', 1],
        ['Surinam', 1],
        ['Trinidad y Tobago', 1],
        ['Uruguay', 1],
        ['Venezuela', 1],

        // Europa
        ['Albania', 2],
        ['Alemania', 2],
        ['Andorra', 2],
        ['Austria', 2],
        ['Bélgica', 2],
        ['Bielorrusia', 2],
        ['Bosnia y Herzegovina', 2],
        ['Bulgaria', 2],
        ['Chipre', 2],
        ['Croacia', 2],
        ['Dinamarca', 2],
        ['Eslovaquia', 2],
        ['Eslovenia', 2],
        ['España', 2],
        ['Estonia', 2],
        ['Finlandia', 2],
        ['Francia', 2],
        ['Grecia', 2],
        ['Hungría', 2],
        ['Irlanda', 2],
        ['Islandia', 2],
        ['Italia', 2],
        ['Letonia', 2],
        ['Liechtenstein', 2],
        ['Lituania', 2],
        ['Luxemburgo', 2],
        ['Macedonia del Norte', 2],
        ['Malta', 2],
        ['Moldavia', 2],
        ['Mónaco', 2],
        ['Montenegro', 2],
        ['Noruega', 2],
        ['Países Bajos', 2],
        ['Polonia', 2],
        ['Portugal', 2],
        ['Reino Unido', 2],
        ['República Checa', 2],
        ['Rumanía', 2],
        ['Rusia', 2],
        ['San Marino', 2],
        ['Serbia', 2],
        ['Suecia', 2],
        ['Suiza', 2],
        ['Ucrania', 2],
        ['Vaticano', 2],

        // Africa
        ['Angola', 3],
        ['Argelia', 3],
        ['Benín', 3],
        ['Botsuana', 3],
        ['Burkina Faso', 3],
        ['Burundi', 3],
        ['Cabo Verde', 3],
        ['Camerún', 3],
        ['Chad', 3],
        ['Comoras', 3],
        ['Costa de Marfil', 3],
        ['Egipto', 3],
        ['Eritrea', 3],
        ['Esuatini', 3],
        ['Etiopía', 3],
        ['Gabón', 3],
        ['Gambia', 3],
        ['Ghana', 3],
        ['Guinea', 3],
        ['Guinea-Bisáu', 3],
        ['Guinea Ecuatorial', 3],
        ['Kenia', 3],
        ['Lesoto', 3],
        ['Liberia', 3],
        ['Libia', 3],
        ['Madagascar', 3],
        ['Malaui', 3],
        ['Malí', 3],
        ['Marruecos', 3],
        ['Mauricio', 3],
        ['Mauritania', 3],
        ['Mozambique', 3],
        ['Namibia', 3],
        ['Níger', 3],
        ['Nigeria', 3],
        ['República Centroafricana', 3],
        ['República del Congo', 3],
        ['República Democrática del Congo', 3],
        ['Ruanda', 3],
        ['Santo Tomé y Príncipe', 3],
        ['Senegal', 3],
        ['Seychelles', 3],
        ['Sierra Leona', 3],
        ['Somalia', 3],
        ['Sudáfrica', 3],
        ['Sudán', 3],
        ['Sudán del Sur', 3],
        ['Tanzania', 3],
        ['Togo', 3],
        ['Túnez', 3],
        ['Uganda', 3],
        ['Yibuti', 3],
        ['Zambia', 3],
        ['Zimbabue', 3],

        // Asia
        ['Afganistán', 4],
        ['Arabia Saudita', 4],
        ['Armenia', 4],
        ['Azerbaiyán', 4],
        ['Baréin', 4],
        ['Bangladés', 4],
        ['Birmania', 4],
        ['Brunéi', 4],
        ['Bután', 4],
        ['Camboya', 4],
        ['Catar', 4],
        ['China', 4],
        ['Corea del Norte', 4],
        ['Corea del Sur', 4],
        ['Emiratos Árabes Unidos', 4],
        ['Filipinas', 4],
        ['Georgia', 4],
        ['India', 4],
        ['Indonesia', 4],
        ['Irak', 4],
        ['Irán', 4],
        ['Israel', 4],
        ['Japón', 4],
        ['Jordania', 4],
        ['Kazajistán', 4],
        ['Kirguistán', 4],
        ['Kuwait', 4],
        ['Laos', 4],
        ['Líbano', 4],
        ['Malasia', 4],
        ['Maldivas', 4],
        ['Mongolia', 4],
        ['Nepal', 4],
        ['Omán', 4],
        ['Pakistán', 4],
        ['Palestina', 4],
        ['Singapur', 4],
        ['Siria', 4],
        ['Sri Lanka', 4],
        ['Tayikistán', 4],
        ['Tailandia', 4],
        ['Timor Oriental', 4],
        ['Turquía', 4],
        ['Turkmenistán', 4],
        ['Uzbekistán', 4],
        ['Vietnam', 4],
        ['Yemen', 4],

        // Oceania
        ['Australia', 5],
        ['Fiyi', 5],
        ['Islas Marshall', 5],
        ['Islas Salomón', 5],
        ['Kiribati', 5],
        ['Micronesia', 5],
        ['Nauru', 5],
        ['Nueva Zelanda', 5],
        ['Palaos', 5],
        ['Papúa Nueva Guinea', 5],
        ['Samoa', 5],
        ['Tonga', 5],
        ['Tuvalu', 5],
        ['Vanuatu', 5],
    ];
    public function run(): void
    {
        foreach (self::$data as $key => $value) {
            $payload = [
                'Nombre' => $value[0],
                'IdContinente' => $value[1],
            ];

            if (isset($value[2])) {
                $payload['IdPais'] = $value[2];
            }

            DB::connection(name: 'matriz')->table('pais')->insert($payload);
        }
    }
}
