<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    static $data = [
        ['Afganistán','5'],
        ['Albania','5'],
        ['Alemania','5'],
        ['Andorra','5'],
        ['Angola','5'],
        ['Antigua y Barbuda','5'],
        ['Arabia Saudita','5'],
        ['Argelia','5'],
        ['Argentina','5'],
        ['Armenia','5'],
        ['Australia','5'],
        ['Austria','5'],
        ['Azerbaiyán','5'],
        ['Bahamas','5'],
        ['Bangladés','5'],
        ['Barbados','5'],
        ['Baréin','5'],
        ['Bélgica','5'],
        ['Belice','5'],
        ['Benín','5'],
        ['Bielorrusia','5'],
        ['Birmania','5'],
        ['Bolivia','1'],
        ['Bosnia y Herzegovina','5'],
        ['Botsuana','5'],
        ['Brasil','1'],
        ['Brunéi','5'],
        ['Bulgaria','5'],
        ['Burkina Faso','5'],
        ['Burundi','5'],
        ['Bután','5'],
        ['Cabo Verde','5'],
        ['Camboya','5'],
        ['Camerún','5'],
        ['Canadá','5'],
        ['Catar','5'],
        ['Chad','5'],
        ['Chile','5'],
        ['China','5'],
        ['Chipre','5'],
        ['Ciudad del Vaticano','5'],
        ['Colombia','1'],
        ['Comoras','5'],
        ['Corea del Norte','5'],
        ['Corea del Sur','5'],
        ['Costa de Marfil','5'],
        ['Costa Rica','5'],
        ['Croacia','5'],
        ['Cuba','5'],
        ['Dinamarca','5'],
        ['Dominica','5'],
        ['Ecuador','1'],
        ['Egipto','5'],
        ['El Salvador','5'],
        ['Emiratos Árabes Unidos','5'],
        ['Eritrea','5'],
        ['Eslovaquia','5'],
        ['Eslovenia','5'],
        ['España','5'],
        ['Estados Unidos','1'],
        ['Estonia','5'],
        ['Etiopía','5'],
        ['Filipinas','5'],
        ['Finlandia','5'],
        ['Fiyi','5'],
        ['Francia','5'],
        ['Gabón','5'],
        ['Gambia','5'],
        ['Georgia','5'],
        ['Ghana','5'],
        ['Granada','5'],
        ['Grecia','5'],
        ['Guatemala','5'],
        ['Guyana','5'],
        ['Guinea','5'],
        ['Guinea ecuatorial','5'],
        ['Guinea-Bisáu','5'],
        ['Haití','5'],
        ['Honduras','5'],
        ['Hungría','5'],
        ['India','5'],
        ['Indonesia','5'],
        ['Irak','5'],
        ['Irán','5'],
        ['Irlanda','5'],
        ['Islandia','5'],
        ['Islas Marshall','5'],
        ['Islas Salomón','5'],
        ['Israel','5'],
        ['Italia','5'],
        ['Jamaica','5'],
        ['Japón','5'],
        ['Jordania','5'],
        ['Kazajistán','5'],
        ['Kenia','5'],
        ['Kirguistán','5'],
        ['Kiribati','5'],
        ['Kuwait','5'],
        ['Laos','5'],
        ['Lesoto','5'],
        ['Letonia','5'],
        ['Líbano','5'],
        ['Liberia','5'],
        ['Libia','5'],
        ['Liechtenstein','5'],
        ['Lituania','5'],
        ['Luxemburgo','5'],
        ['Madagascar','5'],
        ['Malasia','5'],
        ['Malaui','5'],
        ['Maldivas','5'],
        ['Malí','5'],
        ['Malta','5'],
        ['Marruecos','5'],
        ['Mauricio','5'],
        ['Mauritania','5'],
        ['México','1'],
        ['Micronesia','5'],
        ['Moldavia','5'],
        ['Mónaco','5'],
        ['Mongolia','5'],
        ['Montenegro','5'],
        ['Mozambique','5'],
        ['Namibia','5'],
        ['Nauru','5'],
        ['Nepal','5'],
        ['Nicaragua','5'],
        ['Níger','5'],
        ['Nigeria','5'],
        ['Noruega','5'],
        ['Nueva Zelanda','5'],
        ['Omán','5'],
        ['Países Bajos','5'],
        ['Pakistán','5'],
        ['Palaos','5'],
        ['Panamá','5'],
        ['Papúa Nueva Guinea','5'],
        ['Paraguay','1'],
        ['Perú','1'],
        ['Polonia','5'],
        ['Portugal','5'],
        ['Reino Unido','5'],
        ['República Centroafricana','5'],
        ['República Checa','5'],
        ['República de Macedonia','5'],
        ['República del Congo','5'],
        ['República Democrática del Congo','5'],
        ['República Dominicana','5'],
        ['República Sudafricana','5'],
        ['Ruanda','5'],
        ['Rumanía','5'],
        ['Rusia','5'],
        ['Samoa','5'],
        ['San Cristóbal y Nieves','5'],
        ['San Marino','5'],
        ['San Vicente y las Granadinas','5'],
        ['Santa Lucía','5'],
        ['Santo Tomé y Príncipe','5'],
        ['Senegal','5'],
        ['Serbia','5'],
        ['Seychelles','5'],
        ['Sierra Leona','5'],
        ['Singapur','5'],
        ['Siria','5'],
        ['Somalia','5'],
        ['Sri Lanka','5'],
        ['Suazilandia','5'],
        ['Sudán','5'],
        ['Sudán del Sur','5'],
        ['Suecia','5'],
        ['Suiza','5'],
        ['Surinam','5'],
        ['Tailandia','5'],
        ['Tanzania','5'],
        ['Tayikistán','5'],
        ['Timor Oriental','5'],
        ['Togo','5'],
        ['Tonga','5'],
        ['Trinidad y Tobago','5'],
        ['Túnez','5'],
        ['Turkmenistán','5'],
        ['Turquía','5'],
        ['Tuvalu','5'],
        ['Ucrania','5'],
        ['Uganda','5'],
        ['Uruguay','5'],
        ['Uzbekistán','5'],
        ['Vanuatu','5'],
        ['Venezuela','1'],
        ['Vietnam','5'],
        ['Yemen','5'],
        ['Yibuti','5'],
        ['Zambia','5'],
        ['Zimbabue','5'],
    ];
    public function run(): void
    {
        foreach (self::$data as $key => $value) {
            DB::connection(name: 'matriz')->table('pais')->insert([
                'Nombre' => $value[0],
                'IdContinente' => $value[1],
            ]);
        }
    }
}
